metadataPackage_1566422286848/objects/Answer__c.object
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1566596412246/objects/Question__c.object
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1566422286848/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/takeSurvey.cls
public with sharing class takeSurvey {

    //Use @AuraEnabled to enable client- and server-side access to the method
    @AuraEnabled
    public static String serverEcho(String firstName) {
        return ('Hello from the server, ' + firstName);
    }

    @AuraEnabled
    public static Map<String, Object> getInitialData(String surveyId) {
        Map<String, Object> surveyMap = new Map<String, Object>();
        surveyMap.put('name', [SELECT Id, Name FROM Survey__c WHERE Id =:surveyId].Name);

        List<Question__c> records = [SELECT Id, Name, Order_Number__c, Survey__r.Name,
                                        ( 
                                           SELECT Id, Name, Order_Number__c 
                                           FROM Answers__r 
                                           ORDER BY Order_Number__c ASC
                                        )
                                       FROM Question__c 
                                       WHERE Survey__c = :surveyId
                                       ORDER BY Order_Number__c ASC];

        List<Object> questions = new List<Object>();
        for(Question__c record : records) {
            Map<String, Object> questionMap = new Map<String, Object>();
            questionMap.put('id', record.Id);
            questionMap.put('name', record.Name);
            questionMap.put('orderNumber', record.Order_Number__c);

            List<Object> answers = new List<Object>();
            for(Answer__c answer : record.Answers__r) {
                Map<String, Object> answerMap = new Map<String, Object>();
                answerMap.put('id', answer.Id);
                answerMap.put('name', answer.Name);
                answerMap.put('orderNumber', answer.Order_Number__c);
                answerMap.put('selected', true);
                answers.add(answerMap);
            }
            questionMap.put('answers', answers);
            questions.add(questionMap);
        }
        surveyMap.put('questions', questions);



        // ITERIATE OVER QUESTIONS
        // ITERATE OVER QUESTION ANSWERS
        // BUILD AN ANSWER MAP, SET PROPERTY selected TO FALSE
        // PUT THEM IN answers LIST
        // BUIILD A QUESTION MAP
        // PUT THEM IN questions LIST
        // ADD questions TO data MAP
        
        //  {
        //         surveyName: 'A',
        //         questions: [
        //             {
        //                 answers: [
        //                     {
        //                         selected: false
        //                     }
        //                 ]
        //             }
        //         ]
        //  }
        
        // List<Map<String, List<Map<String, Object>>>> questionList = new List<Map<String, List<Map<String, Object>>>>();
        // Map<String, List<Map<String, Object>>> questionMap = new Map<String, List<Map<String, Object>>>();
        // for(Question__c question : questions) {
        //     List<Map<String, Object>> answers = new List<Map<String, Object>>();
        //     for(Answer__c answer : question.Answers__r){
        //         Map<String, Object> answerMap = new Map<String, Object>();
        //         answerMap.put('name', answer.Name);
        //         answerMap.put('id', answer.id);
        //         answerMap.put('orderNumber', answer.Order_Number__c);
        //         answerMap.put('selected', false);
        //         //answerMap.put('surveyName', answer.Question__c.name);
        //         answers.add(answerMap);
        //     }
        //     questionMap.put(question.Name, answers);
            
        // }   
        // questionList.add(questionMap);

        return surveyMap;
    }

    @AuraEnabled
    public static List<Answer__c> prepareSubmission(String surveyId) {//optimize to just a list, no need to use map

        List<Answer__c> answerIds = [SELECT Name, id, Question__c
                                        FROM Answer__c
                                        WHERE Question__r.Survey__c = :surveyId 
                                        ORDER BY Question__c];

        return answerIds;
    }
}