metadataPackage_1566422286848/objects/Answer__c.object
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1566596412246/objects/Question__c.object
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1566422286848/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1566422286848/objects/Taken_Survey__c.object
<CustomObject>
    <label>Taken Survey</label>
    <nameField>
        <label>Taken Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taken Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Taken Surveys</relationshipLabel>
        <relationshipName>Taken_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TakeSurveyTest.cls
@isTest
private class TakeSurveyTest {
     @isTest static void testGetInitialData() {
        //var surveyId = '0054F000001PYnuQAG';
        Survey__c testSurvey = new Survey__c(Name='Who will win next election?');
        Test.startTest();
        insert testSurvey;
        ID testId = testSurvey.id;
        Question__c testQuestion = new Question__c(Name='Will it be you?', Survey__c=testSurvey.id);
        insert testQuestion;
        Answer__c testAnswer = new Answer__c(Name='The answer is yes.', Question__c=testQuestion.id);
        insert testAnswer;
        Test.stopTest();
        Map<String, Object> surveyDataMap = takeSurvey.getInitialData(testId);
        System.assertEquals(surveyDataMap.get('name'), 'Who will win next election?');
        System.assertEquals(surveyDataMap.get('id'), testId);
        List<Object> questionsRetrieved = (List<Object>)surveyDataMap.get('questions');
        Map<String, Object> quest = (Map<String, Object>)questionsRetrieved.get(0);
        System.assertEquals(quest.get('name'), 'Will it be you?');
        //---
    }
    @isTest static void testInsertRecords() {
        Map<String, Object> testSurveyMap = new Map<String, Object>();
        String surveyName = 'Who should you vote for?';
        Survey__c testSurvey = new Survey__c(Name=surveyName);
        Test.startTest();
        insert testSurvey;
        testSurveyMap.put('name',surveyName);
        testSurveyMap.put('id', testSurvey.id);
        Taken_Survey__c testTakenSurvey = new Taken_Survey__c(Name='Who should you vote for?', Survey__c=testSurvey.id);
        insert testTakenSurvey;
        Question__c testQuestion = new Question__c(Name='Are you a good person?', Survey__c=testSurvey.id);
        insert testQuestion;
        Answer__c testAnswer = new Answer__c(Name='No', Question__c=testQuestion.id);
        Map<Object, Object> testQuestionMap = new Map<Object, Object>();
        List<Map<Object, Object>> testQuestions = new List<Map<Object, Object>>();
        List<Object> testAnswers = new List<Object>();
        Map<Object, Object> testAnswerMap = new  Map<Object, Object>();
        testAnswerMap.put('id', testAnswer.id);
        testAnswerMap.put('name', testAnswer.name);
        testAnswerMap.put('selected', true);
        testAnswers.add(testAnswerMap);
        testQuestionMap.put('id', testQuestion.id);
        testQuestionMap.put('answers', testAnswers);
        testQuestions.add(testQuestionMap);
        testSurveyMap.put('questions', testQuestions);
        takeSurvey.insertRecords(testSurveyMap);

        System.assertEquals(testSurveyMap.get('id'), testSurvey.id);

        //var surveyId = '0054F000001PYnuQAG'
    }
    
}