metadataPackage_1566596412246/objects/Question__c.object
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1566596412246/objects/Selected_Answer__c.object
<CustomObject>
    <label>Selected Answer</label>
    <nameField>
        <label>Selected Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selected Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Selected Answers</relationshipLabel>
        <relationshipName>Selected_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taken_Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Taken Survey</label>
        <referenceTo>Taken_Survey__c</referenceTo>
        <relationshipLabel>Selected Answers</relationshipLabel>
        <relationshipName>Selected_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Selected_Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Selected Answers</relationshipLabel>
    <relationshipName>Selected_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

metadataPackage_1566422286848/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1566422286848/objects/Taken_Survey__c.object
<CustomObject>
    <label>Taken Survey</label>
    <nameField>
        <label>Taken Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taken Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Date_Created__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date Created</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Taken Surveys</relationshipLabel>
        <relationshipName>Taken_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ViewMySurveysTest.cls
@isTest
private class ViewMySurveysTest {
     @isTest static void testGetMyTakenSurveys() {
        date mydate = date.parse('12/27/2009');
        Survey__c testSurvey = new Survey__c(Name='Survey Template for testing');
        Taken_Survey__c testTakenSurvey = new Taken_Survey__c(Name='Test Survey 01', Date_Created__c=mydate);
        Test.startTest();
        insert testSurvey;
        insert testTakenSurvey;
        Question__c testQuestion = new Question__c(Name='Did you do it?', Survey__c=testSurvey.id);
        insert testQuestion;
        Selected_Answer__c testAnswer = new Selected_Answer__c(Name='The answer is yes.', Question__c=testQuestion.id);
        insert testAnswer;
        Test.stopTest();
        List<Taken_Survey__c> surveyData = viewMySurveysVF.getMyTakenSurveys('0054F000001PYnuQAG');
        List<Taken_Survey__c> testList = new List<Taken_Survey__c>();
        testList.add(testTakenSurvey);
        System.assertEquals(surveyData, testList);
    }

    @isTest static void testGetSurveysByTemplate() {
        date mydate = date.parse('12/27/2009');
        Taken_Survey__c testTakenSurvey = new Taken_Survey__c(Name='Test Survey 02', Date_Created__c=mydate);
        Test.startTest();
        insert testTakenSurvey;
        Test.stopTest();
        List<Taken_Survey__c> surveyData = viewMySurveysVF.getSurveysByTemplate();
        List<Taken_Survey__c> testList = new List<Taken_Survey__c>();
        testList.add(testTakenSurvey);
        System.assertEquals(surveyData[0].Name, testList[0].Name);
        System.assertEquals(surveyData[0].Name, testList[0].Name);
    }
    
}