metadataPackage_1566596412246/objects/Question__c.object
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1566596412246/objects/Selected_Answer__c.object
<CustomObject>
    <label>Selected Answer</label>
    <nameField>
        <label>Selected Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selected Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Selected Answers</relationshipLabel>
        <relationshipName>Selected_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taken_Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Taken Survey</label>
        <referenceTo>Taken_Survey__c</referenceTo>
        <relationshipLabel>Selected Answers</relationshipLabel>
        <relationshipName>Selected_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1566422286848/objects/Taken_Survey__c.object
<CustomObject>
    <label>Taken Survey</label>
    <nameField>
        <label>Taken Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taken Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Date_Created__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date Created</label>
        <type>Date</type>
    </fields>
</CustomObject>

metadataPackage_1566596412246/classes/viewMySurveysVF.cls
public class viewMySurveysVF {
   	@AuraEnabled
    public static String getData(String userId) {
        responseData rd = new responseData();
        
        try {
            rd.put('userId', userId);
            List<SObject> data = Database.query('SELECT Name, ' + constants.NAMESPACE_API + 'Date_Created__c, (SELECT Name, ' + constants.NAMESPACE_API + 'Question__r.Name FROM ' + constants.NAMESPACE_API + 'Selected_Answers__r) FROM ' + constants.NAMESPACE_API + 'Taken_Survey__c WHERE CreatedById = \'' + userId + '\' ORDER BY ' + constants.NAMESPACE_API + 'Date_Created__c DESC');
            if (data.isEmpty()) {
                System.debug('got no data');
            } else {
                rd.put('data', data);
            }
        } catch(Exception e) {
            System.debug(e);
            rd.addError(e.getMessage());
        }
        return rd.getJsonString();
    }

    @AuraEnabled
    public static String getSurveysByTemplate() {
        responseData rd = new responseData();
        try {
            List<SObject> data = Database.query('SELECT Name, ' + constants.NAMESPACE_API + 'Date_Created__c, CreatedById FROM ' + constants.NAMESPACE_API + 'Taken_Survey__c ORDER BY ' + constants.NAMESPACE_API + 'Date_Created__c DESC');
            if (data.isEmpty()) {
                System.debug('got no data getSurveysByTemplate');
            } else {
                rd.put('data', data);
            }
        } catch(Exception e) {
            rd.addError(e.getMessage());
        }
        return rd.getJsonString();       
    }
}