metadataPackage_1566596412246/objects/Question__c.object
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1566596412246/objects/Selected_Answer__c.object
<CustomObject>
    <label>Selected Answer</label>
    <nameField>
        <label>Selected Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selected Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Selected Answers</relationshipLabel>
        <relationshipName>Selected_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taken_Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Taken Survey</label>
        <referenceTo>Taken_Survey__c</referenceTo>
        <relationshipLabel>Selected Answers</relationshipLabel>
        <relationshipName>Selected_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Selected_Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Selected Answers</relationshipLabel>
    <relationshipName>Selected_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

metadataPackage_1566422286848/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1566422286848/objects/Taken_Survey__c.object
<CustomObject>
    <label>Taken Survey</label>
    <nameField>
        <label>Taken Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taken Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Date_Created__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date Created</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Taken Surveys</relationshipLabel>
        <relationshipName>Taken_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/viewMySurveysVF.cls
public class viewMySurveysVF {
    public String namespace { get; set; }

    public viewMySurveysVF() {
        namespace = constants.NAMESPACE;
    }

    public String getNamespaceApi() {
        return constants.NAMESPACE_API;
    }
    
   	@AuraEnabled
    public static String getData(String userId) {
        responseData rd = new responseData();
        
        try {
            rd.put('userId', userId);
            //List<SObject> data = Database.query('SELECT Id, Name FROM ' + constants.NAMESPACE_API + 'Survey__c');
            List<SObject> data = Database.query('SELECT Name, ' + constants.NAMESPACE_API + 'Date_Created__c, (SELECT Name, ' + constants.NAMESPACE_API + 'Question__r.Name FROM ' + constants.NAMESPACE_API + 'Selected_Answers__r) FROM ' + constants.NAMESPACE_API + 'Taken_Survey__c ORDER BY ' + constants.NAMESPACE_API + 'Date_Created__c DESC');
            //List<SObject> data = Database.query('SELECT Name, ' + constants.NAMESPACE_API + 'Date_Created__c, (SELECT Name, ' + constants.NAMESPACE_API + 'Question__r.Name FROM ' + constants.NAMESPACE_API + 'Selected_Answers__r) FROM ' + constants.NAMESPACE_API + 'Taken_Survey__c WHERE CreatedById = ' + userId + ' ORDER BY ' + constants.NAMESPACE_API + 'Date_Created__c DESC');
            if (data.isEmpty()) {
                System.debug('got no data');
            } else {
                rd.put('data', data);
            }
        } catch(Exception e) {
            rd.addError(e.getMessage());
        }
        return rd.getJsonString();
    }
    
    @AuraEnabled
    public static List<Taken_Survey__c> getMyTakenSurveys(String userId) {
        return [SELECT Name, Date_Created__c, 
                (
                    SELECT Name, Question__r.Name FROM Selected_Answers__r
                )
                FROM Taken_Survey__c
                WHERE CreatedById = :userId
                ORDER BY Date_Created__c DESC];         
    }

    @AuraEnabled
    public static List<Taken_Survey__c> getSurveysByTemplate() {
        return [SELECT Name, Date_Created__c, CreatedById
                FROM Taken_Survey__c
                ORDER BY Date_Created__c DESC];           
    }
}